WITH CTE_MINDATE
AS 
(
	SELECT
		CAST(VALUE AS DATETIME) AS MINDATE
	FROM {{ source('meta_model', 'T_CONFIGURATION') }}
	WHERE UPPER(NAME) = 'DATEMINVALUE'
),
CTE_MAXDATE
AS 
(
	SELECT
		CAST(VALUE AS DATETIME) AS MAXDATE
	FROM {{ source('meta_model', 'T_CONFIGURATION') }}
	WHERE UPPER(NAME) = 'DATEMAXVALUE'
),
FINAL
AS 
(
    select 
        (SELECT MINDATE BizBeg FROM CTE_MINDATE) BizBeg,
        (SELECT MAXDATE BizEnd FROM CTE_MAXDATE) BizEnd
)
select * from FINAL
